@baseUrl = https://8080-dennisfaria-atividadepr-kykh2clerx8.ws-us115.gitpod.io/

###
GET {{baseUrl}}/tarefas

###
POST {{baseUrl}}/tarefas
Content-Type: application/json

{
    "descricao": "Atividade 1",
    "concluido": true
}

###
GET {{baseUrl}}/tarefas/5

###
PUT {{baseUrl}}/tarefas/4
Content-Type: application/json

{
    "descricao": "Atividade 1",
    "concluido": false
}

###
DELETE {{baseUrl}}/tarefas/5